
#Server configuration settings
[server]
	#Changes if entities are recognized as hostile by other mods. See https://github.com/TeamLapen/Vampirism/issues/199. Smart falls back to Never on servers 
	#Allowed Values: ALWAYS_IMOB, NEVER_IMOB, SMART
	entitiesIMob = "SMART"
	#Block radius the sunscreen beacon affects
	#Range: 1 ~ 40000
	sunscreenBeaconDistance = 32
	#Whether the suncreen beacon can be mined in survival
	sunscreenBeaconMineable = false
	#If PVP should only be allowed between factions. PVP has to be enabled in the server properties for this. Not guaranteed to always protect player from teammates
	pvpOnlyBetweenFactions = false
	#If enabled, creatures are infected with Sanguinare Vampirism first instead of immediately being converted to a vampire when their blood is sucked dry
	infectCreaturesSanguinare = false
	#Whether to color player names in chat based on their current faction
	factionColorInChat = true
	#Prevent clients from disabling the vampire forest fog
	enforceForestFog = true
	#If vampires can convert to a bat in the End
	batModeInEnd = false
	#Whether to add a prefix title based on the current lord level to the player names
	lordPrefixInChat = true
	#Calculate the blood level for unknown creatures based on their size
	autoCalculateEntityBlood = true
	#Whether players can infect other players
	playersCanTurnPlayers = true

	[server.internal]
		#Send message about Guide-API once
		infoAboutGuideAPI = true
		#If world was generated using the old vampirism biome
		oldVampireBiomeGen = true

	[server.entities]
		#Blacklist entities from predefined or auto calculated blood values
		blacklistedBloodEntity = []

	#Disabling these things might reduce fun or interfere with gameplay
	[server.disable]
		#Prevent vampire mobs from infecting players when attacking
		disableMobBiteInfection = false
		#Disable vampire fangs being usable to infect yourself
		disableFangInfection = false
		#Disable hunter camp generation
		disableHunterTentGen = false

	[server.sundamage]
		#Additional biomes the player should not get sundamage in. Use biome ids e.g. ["minecraft:mesa", "minecraft:plains"]
		sundamageDisabledBiomes = []
		#Add the string id in quotes of any dimension (/vampirism currentDimension) you want to enforce sundamage for to this comma-separated list. Overrides defaults and values added by other mods
		sundamageDimensionsOverridePositive = []
		#Add the string id in quotes of any dimension (/vampirism currentDimension) you want to disable sundamage for to this comma-separated list. Overrides defaults and values added by other mods
		sundamageDimensionsOverrideNegative = []
		#Whether vampires should receive sundamage in unknown dimensions
		sundamageUnknownDimension = false

	[server.cheats]
		#CHEAT: If enabled, you will be able to unlock all skills at max level
		allSkillsAtMaxLevel = false

	[server.village]
		#Desired maximum distance between villages in chunks
		#Range: 1 ~ 100
		villageDistance = 26
		#Minimum distance between villages in chunks. Must be smaller than distance
		#Range: 1 ~ 100
		villageSeparation = 6

